<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE vtkConf [
<!ELEMENT vtkConf (info,configuration*, module*, reference*)>

   <!ELEMENT info (vtkConfigurationsVersion,projectName)>
       <!ELEMENT vtkConfigurationsVersion (#PCDATA)>
       <!ELEMENT projectName (#PCDATA)>

   <!ELEMENT configuration (name,path,templatePath?,title?,comment?)>
    <!ATTLIST configuration cID ID #REQUIRED>
       <!ELEMENT name (#PCDATA)>
       <!ELEMENT path (#PCDATA)>
       <!ELEMENT templatePath (#PCDATA)>
       <!ELEMENT title (#PCDATA)>
       <!ELEMENT comment (#PCDATA)>

   <!ELEMENT module (name, modulePath*)>
    <!ATTLIST module mID ID #REQUIRED>
       <!ELEMENT modulePath (#PCDATA)>
       <!ATTLIST modulePath
           confId IDREF #REQUIRED
       >

   <!ELEMENT reference (name, (guid|path))>
    <!ATTLIST reference confIDs IDREFS #REQUIRED>
       <!ELEMENT guid (#PCDATA)>
]>
<vtkConf>
	<info>
		<vtkConfigurationsVersion>1.0</vtkConfigurationsVersion>
		<projectName>TestProject</projectName>
	</info>

	<configuration cID="c01">
		<name>TestProject</name>
		<path>Delivery\TestProject.xlsm</path>
	</configuration>

	<configuration cID="c02">
		<name>TestProject_DEV</name>
		<path>Project\TestProject_DEV.xlsm</path>
	</configuration>


	<module mID="m01">
		<name>TestModule1</name>
		<modulePath confId="c02">Project\TestModule1.bas</modulePath>
	</module>


	<module mID="m02">
		<name>TestModule2</name>
		<modulePath confId="c02">Project\TestModule2.bas</modulePath>
	</module>


</vtkConf>