<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE vtkConf [
<!ELEMENT vtkConf (info,configuration*, module*, reference*)>

   <!ELEMENT info (vtkConfigurationsVersion,projectName)>
       <!ELEMENT vtkConfigurationsVersion (#PCDATA)>
       <!ELEMENT projectName (#PCDATA)>

   <!ELEMENT configuration (name,path,templatePath?,title?,comment?)>
    <!ATTLIST configuration cID ID #REQUIRED>
       <!ELEMENT name (#PCDATA)>
       <!ELEMENT path (#PCDATA)>
       <!ELEMENT templatePath (#PCDATA)>
       <!ELEMENT title (#PCDATA)>
       <!ELEMENT comment (#PCDATA)>

   <!ELEMENT module (name, modulePath*)>
    <!ATTLIST module mID ID #REQUIRED>
       <!ELEMENT modulePath (#PCDATA)>
       <!ATTLIST modulePath
           confId IDREF #REQUIRED
       >

   <!ELEMENT reference (name, (guid|path))>
    <!ATTLIST reference confIDs IDREFS #REQUIRED>
       <!ELEMENT guid (#PCDATA)>
]>
<vtkConf>

	<info>
		<vtkConfigurationsVersion>1.0</vtkConfigurationsVersion>
		<projectName>TestProjectForRecreateCOnfiguration</projectName>
	</info>

	<configuration cID="c01">
		<name>TestProject</name>
		<path>TestProject.xlsm</path>
	</configuration>

	<configuration cID="c02">
		<name>TestProject_DEV</name>
		<path>TestProject_DEV.xlsm</path>
	</configuration>

	<configuration cID="c03">
		<name>TestProject_notExistingPathConf1</name>
		<path>testFolder1\TestProject_notExistingPathConf1.xlsm</path>
	</configuration>

	<configuration cID="c04">
		<name>TestProject_notExistingPathConf2</name>
		<path>testFolder1\testFolder2\TestProject_notExistingPathConf2.xlsm</path>
	</configuration>

	<configuration cID="c05">
		<name>TestProject_emptyConf</name>
		<path>TestProject_emptyConf.xlsm</path>
	</configuration>

	<configuration cID="c06">
		<name>TestProject_normalConf</name>
		<path>TestProject_normalConf.xlsm</path>
		<title>Normal Conf</title>
		<comment>This conf is normal</comment>
	</configuration>

	<configuration cID="c07">
		<name>TestProject_xlamConf</name>
		<path>TestProject_xlamConf.xlam</path>
	</configuration>

	<configuration cID="c08">
		<name>TestProject_xlsConf</name>
		<path>TestProject_xlsConf.xls</path>
	</configuration>

	<configuration cID="c09">
		<name>TestProject_xlaConf</name>
		<path>TestProject_xlaConf.xla</path>
	</configuration>

	<configuration cID="c10">
		<name>TestProject_multitypeConf</name>
		<path>TestProject_multitypeConf.xlsm</path>
	</configuration>

	<configuration cID="c11">
		<name>TestProject_VTKConf</name>
		<path>VBAToolKit.xlam</path>
	</configuration>

	<configuration cID="c12">
		<name>VBAToolKit</name>
		<path>VBAToolKit.xlam</path>
	</configuration>

	<configuration cID="c13">
		<name>TestProject_faultyRefConf</name>
		<path>TestProject_faultyRefConf.xlsm</path>
	</configuration>

	<configuration cID="c14">
		<name>TestProject_xlsmTemplateConf</name>
		<path>TestProject_xlsmTemplateConf.xlsm</path>
		<templatePath>xlsmTemplateWorkbook.xlsm</templatePath>
	</configuration>

	<configuration cID="c15">
		<name>TestProject_xlamTemplateConf</name>
		<path>TestProject_xlamTemplateConf.xlam</path>
		<templatePath>xlamTemplateWorkbook.xlam</templatePath>
	</configuration>

	<configuration cID="c16">
		<name>TestProject_xlaTemplateConf</name>
		<path>TestProject_xlaTemplateConf.xla</path>
		<templatePath>xlaTemplateWorkbook.xla</templatePath>
	</configuration>

	<configuration cID="c17">
		<name>TestProject_xlsTemplateConf</name>
		<path>TestProject_xlsTemplateConf.xls</path>
		<templatePath>xlsTemplateWorkbook.xls</templatePath>
	</configuration>

	<module mID="m01">
		<name>TestModule1</name>
		<modulePath confId="c02">TestModule1.bas</modulePath>
		<modulePath confId="c03">TestModule1.bas</modulePath>
		<modulePath confId="c04">TestModule1.bas</modulePath>
		<modulePath confId="c06">TestModule1.bas</modulePath>
		<modulePath confId="c07">TestModule1.bas</modulePath>
		<modulePath confId="c08">TestModule1.bas</modulePath>
		<modulePath confId="c09">TestModule1.bas</modulePath>
		<modulePath confId="c10">TestModule1.bas</modulePath>
		<modulePath confId="c11">TestModule1.bas</modulePath>
		<modulePath confId="c12">TestModule1.bas</modulePath>
	</module>


	<module mID="m02">
		<name>TestModule2</name>
		<modulePath confId="c02">TestModule2.bas</modulePath>
		<modulePath confId="c06">TestModule2.bas</modulePath>
		<modulePath confId="c07">TestModule2.bas</modulePath>
		<modulePath confId="c08">TestModule2.bas</modulePath>
		<modulePath confId="c09">TestModule2.bas</modulePath>
		<modulePath confId="c10">TestModule2.bas</modulePath>
		<modulePath confId="c11">TestModule2.bas</modulePath>
		<modulePath confId="c12">TestModule2.bas</modulePath>
	</module>


	<module mID="m03">
		<name>TestClassModule1</name>
		<modulePath confId="c10">TestClassModule1.cls</modulePath>
	</module>


	<module mID="m04">
		<name>TestFormModule1</name>
		<modulePath confId="c10">TestFormModule1.frm</modulePath>
	</module>

	<reference confIDs="c06">
		<name>Scripting</name>
		<guid>{420B2830-E718-11CF-893D-00A0C9054228}</guid>
	</reference>

	<reference confIDs="c06">
		<name>Shell32</name>
		<guid>{50A7E9B0-70EF-11D1-B75A-00A0C90564FE}</guid>
	</reference>

	<reference confIDs="c13">
		<name>Faulty Ref</name>
		<guid>{dummyGUID}</guid>
	</reference>

</vtkConf>