<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE vtkConf [
<!ELEMENT vtkConf (info,configuration*, module*, reference*)>

   <!ELEMENT info (vtkConfigurationsVersion,projectName)>
       <!ELEMENT vtkConfigurationsVersion (#PCDATA)>
       <!ELEMENT projectName (#PCDATA)>

   <!ELEMENT configuration (name,path,templatePath?,title?,comment?)>
    <!ATTLIST configuration cID ID #REQUIRED>
       <!ELEMENT name (#PCDATA)>
       <!ELEMENT path (#PCDATA)>
       <!ELEMENT templatePath (#PCDATA)>
       <!ELEMENT title (#PCDATA)>
       <!ELEMENT comment (#PCDATA)>

   <!ELEMENT module (name, modulePath*)>
    <!ATTLIST module mID ID #REQUIRED>
       <!ELEMENT modulePath (#PCDATA)>
       <!ATTLIST modulePath
           confId IDREF #REQUIRED
       >

   <!ELEMENT reference (name, (guid|path))>
    <!ATTLIST reference confIDs IDREFS #REQUIRED>
       <!ELEMENT guid (#PCDATA)>
]>
<vtkConf>

	<info>
		<vtkConfigurationsVersion>2.0</vtkConfigurationsVersion>
		<projectName>TestProject1</projectName>
	</info>


	<configuration cID="c01">
		<name>ExistingProject</name>
		<path>Delivery\ExistingProject.xlsm</path>
		<templatePath>C:\Dummy\Template.xlsm</templatePath>
		<title>Existing Project Delivery version</title>
		<comment>This is the Delivery configuration of ExistingProject</comment>
	</configuration>

	<configuration cID="c02">
		<name>ExistingProject_DEV</name>
		<path>Project\ExistingProject_DEV.xlsm</path>
		<templatePath>Templates/TestTemplate.xlsm</templatePath>
		<title>Existing Project DEV version</title>
		<comment>This is the DEV configuration of ExistingProject</comment>
	</configuration>

	<module mID="m01">
		<name>Module1</name>
		<modulePath confId="c01">Path1Module1</modulePath>
	</module>

	<module mID="m02">
		<name>Module2</name>
		<modulePath confId="c02">Path2Module2</modulePath>
	</module>

	<module mID="m03">
		<name>Module3</name>
	</module>

	<module mID="m04">
		<name>Module4</name>
		<modulePath confId="c01">Path1Module4</modulePath>
		<modulePath confId="c02">Path2Module4</modulePath>
	</module>

	<module mID="m05">
		<name>Module5</name>
		<modulePath confId="c01"/>
		<modulePath confId="c02">Path2Module5</modulePath>
	</module>

	<reference confIDs="c02">
		<name>Reference1</name>
		<guid>GuidReference1</guid>
	</reference>

	<reference confIDs="c01 c02">
		<name>Reference2</name>
		<guid>GuidReference2</guid>
	</reference>

	<reference confIDs="c02">
		<name>Reference3</name>
		<path>PathReference3</path>
	</reference>

</vtkConf>